site_name: "Лабораторные работы"
theme:
  name: material
  features:
    - navigation.indexes
    - content.code.copy
  icon:
    repo: fontawesome/brands/github-alt
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/lightbulb
        name: Переключиться на тёмную тему
    - media: "(prefers-color-scheme: dark)"
      primary: cyan
      scheme: slate
      toggle:
        icon: material/lightbulb-outline
        name: Переключиться на светлую тему
  language: ru
repo_url: https://github.com/Alisa-Mikulina/ITMO_ICT_WebDevelopment_2023-2024
markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      restrict_base_path: False
  - pymdownx.superfences
  - pymdownx.keys
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
plugins:
  - glightbox:
      auto_caption: true
extra_css:
- css/custom.css
- css/palette.scss
nav:
  - "Laboratory work 1": 
      - lab1/index.md
      - lab1/task_1/index.md
      - lab1/task_2/index.md
      - lab1/task_3/index.md
      - lab1/task_4/index.md
      - lab1/task_5/index.md
  - "Laboratory work 2":
      - lab2/index.md
      - lab2/models/index.md
      - lab2/forms/index.md
      - lab2/urls/index.md
      - lab2/views/index.md
  - "Laboratory work 3":
      - lab3/index.md
      - lab3/models/index.md
      - lab3/serializers/index.md
      - lab3/views/index.md
      - lab3/urls/index.md
      - lab3/pr3_1/index.md
  - "Laboratory work 4":
      - lab4/index.md
      - lab4/CourseItem/index.md
      - lab4/CoursePage/index.md
      - lab4/CourseTeachItem/index.md
      - lab4/LessonItem/index.md
      - lab4/LessonTeachItem/index.md
      - lab4/LoginForm/index.md
      - lab4/ProfilePage/index.md
      - lab4/RegistrationForm/index.md
      - lab4/SubjectItem/index.md
      - lab4/SubjectTeachItem/index.md
